### PR TITLE
Update main.dart

### PR DESCRIPTION
**Pull request by laniku**
Changes time to more of a demo like time, will change to constantly updated time when on use. Change title to include Alpha, as this isn't quite ready yet. Also making the display a bit more blurry for extra protection.

### CODE REVIEW

**Comment by nmcain** [comment]
Please do not change the displayed name of core applications, that interferes with how dahliaOS handles killing and managing these processes, apart from that good work!

**Comment by laniku** [comment]
Got it, changing name back.

**Comment by nmcain** [comment]
Oh, and you may want to revert the opacity change, you just made the background color darker, you want to change the sigma x and y values to increase blur, they are already very high

**Comment by nmcain** [comment]
oops

**Comment by laniku** [comment]
Fixed the name, and edited sigmas.

**Comment by laniku** [comment]
Wait. It only shows the parts I edited. Is that normal?

**Comment by larsb24** [comment]
Yes, that's how git works

**Comment by nmcain** [comment]
Ok, will merge

**Pull request merged**
